export type Solicitudes = {
    cantDias: number;
    cantDiasHabiles: number;
    cantDiasNoHabiles: number;
    codMes: string;
    detalle: string;
    estado: string;
    estadoVacaciones: string;
    fecDelete: string | null;
    fecFinal: string;
    fecInicial: string;
    fecInsert: string;
    fecSolicitud: string;
    fecUpdate: string | null;
    idEmpleado: number;
    idVacacionesSolicitudes: number;
    tipoVacaciones: string;
    usrDelete: string | null;
    usrInsert: string;
    usrUpdate: string | null;
    id: number
};
export type ArraySolicitudes = Array<Solicitudes>;
export type SolicitudesProceso = {
    alias: string;
    cantDias: number;
    cantDiasHabiles: number;
    cantDiasNoHabiles: number;
    codMes: string;
    detalle: string;
    estado: string;
    fecDelete: string | null;
    fecFinal: string;
    fecInicial: string;
    fecInsert: string;
    fecSolicitud: string;
    fecUpdate: string | null;
    id: number;
    idArea: number;
    idEmpleado: number;
    usrDelete: string | null;
    usrInsert: string;
    usrUpdate: string | null;
};
export type ArraySolicitudesProceso = Array<SolicitudesProceso>;
export type SolicitudesAprobadas = {
    alias: string;
    cantDias: number;
    cantDiasHabiles: number;
    cantDiasNoHabiles: number;
    codMes: string;
    detalle: string;
    estado: string;
    estadoVacaciones: string;
    fecDelete: string | null;
    fecFinal: string;
    fecInicial: string;
    fecInsert: string;
    fecSolicitud: string;
    fecUpdate: string | null;
    idArea: number;
    idEmpleado: number;
    idJefe: number;
    idSolicitudAprobada: number;
    tipoVacaciones: string;
    usrDelete: string | null;
    usrInsert: string;
    usrUpdate: string | null;
    nombreArea: string | null;
    idVacacionesSolicitudes: number  | null;
    id: number
};
export type ArraySolicitudesAprobadas = Array<SolicitudesAprobadas>;